---
# GPIO related variables

# The default variables are for a Common Cathode RGB led.
# The led's red pin is connected to GPIO22
# The led's green pin is connected to GPIO27
# The led's blue is connected to GPIO17
redLedPin: "22"
greenLedPin: "27"
blueLedPin: "17"
# Change the values of ledOn and ledOff for the type of led:
# Common Cathode RGB led, ledOn: "1" and ledOff: "0"
# Common Anode RGB led, ledOn: "0" and ledOff: "1"
ledOn: "1"
ledOff: "0"

red:
  gpioPin: "{{ redLedPin }}"
  ledOn: echo '{{ ledOn }}' > /sys/class/gpio/gpio{{ redLedPin }}/value
  ledOff: echo '{{ ledOff }}' > /sys/class/gpio/gpio{{ redLedPin }}/value

green:
  gpioPin: "{{ greenLedPin }}"
  ledOn: echo '{{ ledOn }}' > /sys/class/gpio/gpio{{ greenLedPin }}/value
  ledOff: echo '{{ ledOff }}' > /sys/class/gpio/gpio{{ greenLedPin }}/value

blue:
  gpioPin: "{{ blueLedPin }}"
  ledOn: echo '{{ ledOn }}' > /sys/class/gpio/gpio{{ blueLedPin }}/value
  ledOff: echo '{{ ledOff }}' > /sys/class/gpio/gpio{{ blueLedPin }}/value

# Possible color combinations
led:
  red: "{{ red.ledOn }} && {{ green.ledOff }} && {{ blue.ledOff }}"
  green: "{{ red.ledOff }} && {{ green.ledOn }} && {{ blue.ledOff }}"
  blue: "{{ red.ledOff }} && {{ green.ledOff }} && {{ blue.ledOn }}"
  yellow: "{{ red.ledOn }} && {{ green.ledOn }} && {{ blue.ledOff }}"
  magenta: "{{ red.ledOn }} && {{ green.ledOff }} && {{ blue.ledOn }}"
  cyan: "{{ red.ledOff }} && {{ green.ledOn }} && {{ blue.ledOn }}"
  white: "{{ red.ledOn }} && {{ green.ledOn }} && {{ blue.ledOn }}"
  off: "{{ red.ledOff }} && {{ green.ledOff }} && {{ blue.ledOff }}"
